platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: latest

inputs:
  - name: source-code

outputs:
  - name: source-code-built

run:
  path: sh
  args: 
  - -exc
  - |
    cd source-code
    gradle assemble
    ls - la
  	
params:
  TERM: -dumb
  GRADLE_OPTS: -Dorg.gradle.native=false
