platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: latest

inputs:
  - name: source-code

outputs:
  - name: source-code-built

run:
  path: sh
  args:
  - -exc
  - |
    echo cd source-code
    echo source-code/build.gradle assemble
    ls - la
    echo cp ./build/libs/spring-music.jar source-code-built/spring-music.jar

params:
  TERM: -dumb
  GRADLE_OPTS: -Dorg.gradle.native=false
