platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: latest

inputs:
  - name: source-code

outputs:
  - name: source-code-built

run:
  path: "source-code/gradlew"
  args: ["--build-file", "source-code/build.gradle", "assemble", "cp ./builds/libs/spring-music.jar /tmp/build/put/source-code-built/spring-music.jar"]

params:
  TERM: -dumb
  GRADLE_OPTS: -Dorg.gradle.native=false
