resources:
  - name: source-code
    type: git
    source:
      uri: https://github.com/davidk355/sm-test.git
      branch: master

  - name: resource-deploy-web-app
    type: cf
    source:
      api: {{cf-local-api}}
      username: {{cf-local-username}}
      password: {{cf-local-password}}
      organization: {{cf-local-organization}}
      space: {{cf-local-space}}
      skip_cert_check: true

  - name: resource-deploy-web-app-pws
    type: cf
    source:
      api: https://api.run.pivotal.io
      username: dkari@pivotal.io
      password: Dkvt140611
      organization: DK-Development
      space: development
      skip_cert_check: true

jobs:
  - name: job-deploy-app
    serial: true
    plan:
    - {get: source-code, trigger: true}
    - task: package
      privileged: true
      file: source-code/ci/tasks/package.yml
    - put: resource-deploy-web-app
      params:
        manifest: source-code/manifest.yml
        path: source-code-built/spring-music.jar
    - put: resource-deploy-web-app-pws
      params:
        manifest: source-code/manifest.yml
        path: source-code-built/spring-music.jar
